export const SET_IS_MENU_OPEN = "SET_IS_MENU_OPEN";

export const SET_IS_TOKEN_CALL_LOADING = "SET_IS_TOKEN_CALL_LOADING";
export const SET_TOKEN_CALL_ERROR = "SET_TOKEN_CALL_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";

export const SET_INITIALIZATION_STATUS = "SET_INITIALIZATION_STATUS";

export const REGISTER_STATUS = "REGISTER_STATUS";

export const SET_PROD_STATUS = "SET_PROD_STATUS";

export const SET_USER_INFO = "SET_USER_INFO";
export const READ_PROFILE_STATUS = "READ_PROFILE_STATUS";
export const UPDATE_PROFILE_STATUS = "UPDATE_PROFILE_STATUS";

export const SET_BUSINESS_INFO = "SET_BUSINESS_INFO";
export const READ_BUSINESS_STATUS = "READ_BUSINESS_STATUS";
export const UPDATE_BUSINESS_STATUS = "UPDATE_BUSINESS_STATUS";

export const HOME_PAGE_STATUS = "HOME_PAGE_STATUS";
export const SET_HOME_PAGE = "SET_HOME_PAGE";

export const SUPPORT_STATUS = "SUPPORT_STATUS";
export const SUPPORT_OPEN = "SUPPORT_OPEN";

export const APPLICATION_STAGE = "APPLICATION_STAGE";
export const GET_APPLICATION_STAGE_STATUS = "GET_APPLICATION_STAGE_STATUS";
export const UPDATE_APPLICATION_STAGE_STATUS =
  "UPDATE_APPLICATION_STAGE_STATUS";
