export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_LOCATIONS_STATUS = "GET_LOCATIONS_STATUS";

export const SELECTED_LOCATION = "SELECTED_LOCATION";
export const GET_LOCATION_DETAILS_STATUS = "GET_LOCATION_DETAILS_STATUS";
export const UPDATE_LOCATION_STATUS = "UPDATE_LOCATION_STATUS";
export const DELETE_LOCATION_STATUS = "DELETE_LOCATION_STATUS";
export const CREATE_LOCATION_STATUS = "CREATE_LOCATION_STATUS";
