export const SET_TEMPLATES = "SET_TEMPLATES";
export const GET_TEMPLATES_STATUS = "GET_TEMPLATES_STATUS";
export const SELECTED_TEMPLATE = "SELECTED_TEMPLATE";
export const SET_CREATE_DOC_STATUS = "SET_CREATE_DOC_STATUS";

export const SET_LABEL_LOCATION = "SET_LABEL_LOCATION";
export const TOGGLE_LABEL_ITEM = "TOGGLE_LABEL_ITEM";
export const CLEAR_LABEL_ITEMS = "CLEAR_LABEL_ITEMS";

export const TOGGLE_CARD_LOCATION = "TOGGLE_CARD_LOCATION";
export const CLEAR_CARD_LOCATIONS = "CLEAR_CARD_LOCATIONS";

export const GET_LINKS_STATUS = "GET_LINKS_STATUS";
export const SET_PRINT_LINKS = "SET_PRINT_LINKS";

export const DELETE_LINK_STATUS = "DELETE_LINK_STATUS";
