export const INITIALIZE_LOCATIONS_GOODS = "INITIALIZE_LOCATIONS_GOODS";

export const SET_LOCATIONS_GOODS = "SET_LOCATIONS_GOODS";
export const SET_ALL_GOODS = "SET_ALL_GOODS";

export const SELECTED_GOOD = "SELECTED_GOOD";
export const READ_GOOD_STATUS = "READ_GOOD_STATUS";
export const UPDATE_GOOD_STATUS = "UPDATE_GOOD_STATUS";
export const CREATE_GOOD_STATUS = "CREATE_GOOD_STATUS";
export const UPLOAD_SELECTED_IMAGE_STATUS = "UPLOAD_SELECTED_IMAGE_STATUS";
export const UPLOAD_GOOD_IMAGE_QR = "UPLOAD_GOOD_IMAGE_QR";
