export const GET_REPORTS_STATUS = "GET_REPORTS_STATUS";
export const REPORTS_RES = "REPORTS_RES";

export const SET_ALL_REPORTS = "SET_ALL_REPORTS";
export const SET_ALL_LOCATIONS = "SET_ALL_LOCATIONS";

export const SET_TOTAL_SUM = "SET_TOTAL_SUM";
export const SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT";
