export const GET_ALL_ADDITIONS = "GET_ALL_ADDITIONS";
export const GET_ALL_LOCATION_ITEMS = "GET_ALL_LOCATION_ITEMS";
export const CREATE_ADDITION = "CREATE_ADDITION";
export const UPDATE_ADDITION = "UPDATE_ADDITION";
export const DELETE_ADDITION = "DELETE_ADDITION";