export const GET_ALL_REWARDS = "GET_ALL_REWARDS";
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const GET_LINKED_REWARDS = "GET_LINKED_REWARDS";
export const SET_ALL_ITEMS = "SET_ALL_ITEMS";
export const SET_LINKED_REWARDS = "SET_LINKED_REWARDS";
export const CREATE_REWARD = "CREATE_REWARD";
export const UPDATE_REWARD = "UPDATE_REWARD";
export const DELETE_REWARD = "DELETE_REWARD";